import React from "react";
import { View, StyleSheet, Text } from "react-native";
export const tagsCode = [
  (backgroundColor = "bg"),
  (theme = "t"),
  (windowTheme = "wt"),
  (language = "l"),
  (dropShadow = "ds"),
  (dropShadowOffsetY = "dsyoff"),
  (dropShadowBlur = "dsblur"),
  (windowControl = "wc"),
  (widthAdjustment = "wa"),
  (paddingVertical = "pv"),
  (paddingHorizontal = "ph"),
  (lineNumber = "ln"),
  (fontStart = "fl"),
  (fontFamily = "fm"),
  (fontSize = "fs"),
  (lineHeight = "lh"),
  (squaredImage = "si"),
  (exportSize = "es"),
  (watermark = "wm"),

  ///fl missing
];

export const BASE_URL = "https://carbon.now.sh/?";

export const tagsValue = [
  (bg = "rgba%28171%2C184%2C195%2C1%29"),
  (t = "material"),
  (wt = "sharp"),
  (l = "auto"),
  (ds = "false"),
  (dsyoff = "0px"),
  (dsblur = "0px"),
  (wc = "true"),
  (wa = "false"),
  (pv = "0"),
  (ph = "0"),
  (ln = "false"),
  (fl = "1"),
  (fm = "Hack"),
  (fs = "18px"),
  (lh = "110%"),
  (si = "false"),
  (es = "2x"),
  (wm = "false"),
  (squaredImage = false),
  (hiddenCharacters = false),
  (name = ""),
  (width = "700"),
];
export const themes = [
  { name: "3024 Night", id: "3024-night", background: "#090300" },
  { name: "A11y Dark", id: "a11y-dark", background: "#2B2B2B" },
  { name: "Blackboard", id: "blackboard", background: "#0C1021" },
  { name: "Base 16 (Dark)", id: "base16-dark", background: "#151515" },
  { name: "Base 16 (Light)", id: "base16-light", background: "#F5F5F5" },
  { name: "Cobalt", id: "cobalt", background: "#002240" },
  { name: "Dracula Pro", id: "dracula-pro", background: "#22212C" },
  { name: "Duotone", id: "duotone-dark", background: "#2A2734" },
  { name: "Hopscotch", id: "hopscotch", background: "#322931" },
  { name: "Lucario", id: "lucario", background: "#2B3E50" },
  { name: "Material", id: "material", background: "#263238" },
  { name: "Monokai", id: "monokai", background: "#272822" },
  { name: "Night Owl", id: "night - owl", background: "#011627" },
  { name: "Nord", id: "nord", background: "#2E3440" },
  { name: "Oceanic Next", id: "oceanic-next", background: "#304148" },
  { name: "One Light", id: "one-light", background: "#FAFAFA" },
  { name: "One Dark", id: "one-dark", background: "#282C34" },
  { name: "Panda", id: "panda-syntax", background: "#292A2B" },
  { name: "Paraiso", id: "paraiso-dark", background: "#2F1E2E" },
  { name: "Seti", id: "seti", background: "#151718" },
  { name: "Shades of Purple ", id: "shades-of-purple", background: "#2D2B55" },
  { name: "Solarized (Dark)", id: "solarized+dark", background: "#002B36" },
  { name: "Solarized (Light)", id: "solarized+light", background: "#FDF6E3" },
  { name: "SynthWave '84", id: "synthwave-84", background: "#2B213A" },
  { name: "Twilight", id: "twilight", background: "#141414" },
  { name: "Verminal", id: "verminal", background: "#000000" },
  { name: "VSCode", id: "vscode", background: "#1E1E1E" },
  { name: "Yeti", id: "yeti", background: "#ECEAE8" },
  { name: "Zenburn", id: "zenburn", background: "#3F3F3F" },
];

const styles = StyleSheet.create({});
